AWSTemplateFormatVersion: '2010-09-09'
Description: >
  btl.run CDN Stack
  CloudFront distribution and Route 53 configuration

Parameters:
  Environment:
    Type: String
    Description: Deployment environment

  FrontendBucketName:
    Type: String
    Description: S3 bucket name for frontend assets

  FrontendBucketArn:
    Type: String
    Description: S3 bucket ARN for frontend assets

  FrontendBucketDomainName:
    Type: String
    Description: S3 bucket regional domain name

  ApiEndpoint:
    Type: String
    Description: API Gateway endpoint URL

  DomainName:
    Type: String
    Default: ""
    Description: Custom domain name (e.g., btl.run)

  HostedZoneId:
    Type: String
    Default: ""
    Description: Route 53 Hosted Zone ID

  CertificateArn:
    Type: String
    Default: ""
    Description: Existing ACM certificate ARN (must be in us-east-1 for CloudFront)

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, ""]]
  CreateCertificate: !And
    - !Not [!Equals [!Ref DomainName, ""]]
    - !Equals [!Ref CertificateArn, ""]
  UseExistingCertificate: !And
    - !Not [!Equals [!Ref DomainName, ""]]
    - !Not [!Equals [!Ref CertificateArn, ""]]

Resources:
  # CloudFront Function to rewrite /mocks/folder/ to /mocks/folder/index.html
  # This is needed because S3 + OAC doesn't support default index documents
  MocksIndexFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "btl-run-mocks-index-${Environment}"
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;
          
          // If URI ends with / or has no extension, append index.html
          if (uri.endsWith('/')) {
            request.uri = uri + 'index.html';
          } else if (!uri.includes('.')) {
            // No file extension - treat as directory
            request.uri = uri + '/index.html';
          }
          
          return request;
        }
      FunctionConfig:
        Comment: Rewrite mocks directory requests to index.html
        Runtime: cloudfront-js-2.0

  # CloudFront Origin Access Control for S3
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "btl-run-oac-${Environment}"
        Description: OAC for btl.run frontend bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "btl.run ${Environment} distribution"
        Enabled: true
        HttpVersion: http2and3
        PriceClass: PriceClass_100
        DefaultRootObject: index.html

        # Custom domain (if provided)
        Aliases: !If
          - HasCustomDomain
          - [!Ref DomainName]
          - !Ref AWS::NoValue

        ViewerCertificate: !If
          - UseExistingCertificate
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - !If
            - CreateCertificate
            - AcmCertificateArn: !Ref Certificate
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2021
            - CloudFrontDefaultCertificate: true

        # S3 origin for frontend
        Origins:
          - Id: S3Origin
            DomainName: !Ref FrontendBucketDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ""

          # API Gateway origin
          - Id: ApiOrigin
            DomainName: !Select
              - 2
              - !Split ["/", !Ref ApiEndpoint]
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

        # Default behavior (S3)
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # Managed-CachingOptimized
          ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03  # Managed-SecurityHeadersPolicy

        # Cache behaviors (order matters - more specific patterns first)
        CacheBehaviors:
          # Static mockups - no SPA fallback, serve files directly
          # Note: CustomErrorResponses is distribution-wide, but mockups should
          # exist as actual files. If a mock file is missing, it will fall back
          # to index.html. Ensure all mock files are deployed.
          - PathPattern: /mocks/*
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            # Use short TTL for mockups to allow easy iteration
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # Managed-CachingOptimized
            ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
            FunctionAssociations:
              - EventType: viewer-request
                FunctionARN: !GetAtt MocksIndexFunction.FunctionARN

          - PathPattern: /api/*
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # Managed-AllViewerExceptHostHeader
            ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03

          - PathPattern: /health
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac

        # SPA routing - serve index.html for 404s
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10

      Tags:
        - Key: Project
          Value: btl-run
        - Key: Environment
          Value: !Ref Environment

  # ACM Certificate (only if custom domain provided but no certificate ARN)
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateCertificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Project
          Value: btl-run
        - Key: Environment
          Value: !Ref Environment

  # Route 53 DNS record (only if custom domain is provided)
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)

Outputs:
  CloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution

  CloudFrontDistributionArn:
    Description: CloudFront distribution ARN
    Value: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
