AWSTemplateFormatVersion: '2010-09-09'
Description: >
  btl.run Storage Stack
  S3 buckets for frontend hosting and deployment artifacts

Parameters:
  Environment:
    Type: String
    Description: Deployment environment

Resources:
  # S3 bucket for frontend static files
  FrontendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "btl-run-frontend-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: CleanupOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Project
          Value: btl-run
        - Key: Environment
          Value: !Ref Environment

  # Bucket policy for CloudFront OAC access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringLike:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"

  # S3 bucket for deployment artifacts (Lambda code, etc.)
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "btl-run-artifacts-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: CleanupOldArtifacts
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Project
          Value: btl-run
        - Key: Environment
          Value: !Ref Environment

Outputs:
  FrontendBucketName:
    Description: Frontend S3 bucket name
    Value: !Ref FrontendBucket

  FrontendBucketArn:
    Description: Frontend S3 bucket ARN
    Value: !GetAtt FrontendBucket.Arn

  FrontendBucketDomainName:
    Description: Frontend S3 bucket regional domain name
    Value: !GetAtt FrontendBucket.RegionalDomainName

  ArtifactsBucketName:
    Description: Artifacts S3 bucket name
    Value: !Ref ArtifactsBucket

  ArtifactsBucketArn:
    Description: Artifacts S3 bucket ARN
    Value: !GetAtt ArtifactsBucket.Arn
